Add --checks-only to crc setup
code-ready/crc pull request #2179
Opened 2021-04-02 10:16 UTC by cfergeau

This adds a way of checking if `crc setup` has to be run before `crc
start` can be called:

$ ./crc setup --checks-only
INFO Checking if running as non-root
INFO Checking if podman remote executable is cached
INFO Checking if admin-helper executable is cached
admin-helper executable is not cached

$ echo $?
2

$ ./crc setup --checks-only -ojson
INFO Checking if running as non-root
INFO Checking if podman remote executable is cached
INFO Checking if admin-helper executable is cached
{
  "success": false,
  "error": "admin-helper executable is not cached"
}

$ echo $?
0

This should fix https://github.com/code-ready/crc/issues/2170

2021-04-02 10:18 UTC, cfergeau commented
Let's make sure this fits jboss tools need before getting this in, as we don't need this option if it's not useful to them.

2021-04-02 10:46 UTC, gbraad commented
what does ` --checks-only ` only mean? There is a plural in here that just what? I believe this should be `--check-only`, but using `--only-run-checks` would be more indicative of what happens

@robin-owen Any suggestions?

2021-04-02 10:48 UTC, cfergeau commented
Could also be the opposite, something like `--no-fixes`
Just tell me what flag to use and I'll make the change.

2021-04-02 10:49 UTC, gbraad commented
the `--no-fixes` is not indicative to the user. this is more about how we implemented this.

2021-04-02 18:47 UTC, jsliacan commented
@cfergeau , so the exitcode always refers to the last option? I.e. would above example with `crc setup -ojson --checks-only` yield exitcode 2? Thanks

2021-04-06 08:32 UTC, cfergeau commented
> EDIT: So I tried it and if you add -ojson flag anywhere it returns exitcode 0 (provided all goes OK, even though crc setup --check-only would give 2). What's the rule for these things?

Yeah the return value with `-ojson` seems to always be 0, but this is already the case before this change. The json itself describes the error, so I'm not sure this is a problem.

2021-04-07 05:47 UTC, gbraad commented
Please update test description, commit description and title to reflect recent changes

2021-04-07 05:48 UTC, gbraad requested changes
Commit descriptions are inconsistent with the code

2021-04-07 09:36 UTC, cfergeau commented
> Commit descriptions are inconsistent with the code

I changed the `checks-only` occurrences if this was the inconsistency you refer to.

2021-04-07 11:48 UTC, cfergeau commented
/retest

2021-04-08 14:47 UTC, cfergeau commented
/retest

2021-04-09 05:24 UTC, praveenkumar commented
With current state following happen if there is no issue with preflight checks. Here `Setup is complete, you can now run 'crc start -b $bundlename' to start the OpenShift cluster` output is bit confusing and doesn't make sense because we are only running the preflight checks so better not to have this message when `check-only` option in used.

```
$ ./crc setup --check-only
[...]
INFO Checking if libvirt 'crc' network is active  
Setup is complete, you can now run 'crc start -b $bundlename' to start the OpenShift cluster
```

I think this should do it.

```patch
diff --git a/cmd/crc/cmd/setup.go b/cmd/crc/cmd/setup.go
index e8cf8098..1b5322ad 100644
--- a/cmd/crc/cmd/setup.go
+++ b/cmd/crc/cmd/setup.go
@@ -82,6 +82,9 @@ func (s *setupResult) prettyPrintTo(writer io.Writer) error {
        if s.Error != nil {
                return s.Error
        }
+       if checksOnly {
+               return nil
+       }
        _, err := fmt.Fprintf(writer, "Setup is complete, you can now run 'crc start%s' to start the OpenShift cluster\n", extraArguments())
        return err
 }
```

2021-04-09 08:06 UTC, jsliacan commented
> With current state following happen if there is no issue with preflight checks. Here `Setup is complete, you can now run 'crc start -b $bundlename' to start the OpenShift cluster` output is bit confusing and doesn't make sense because we are only running the preflight checks so better not to have this message when `check-only` option in used.
> 
> ```
> $ ./crc setup --check-only
> [...]
> INFO Checking if libvirt 'crc' network is active  
> Setup is complete, you can now run 'crc start -b $bundlename' to start the OpenShift cluster
> ```
> 
> I think this should do it.
> 
> ```diff
> diff --git a/cmd/crc/cmd/setup.go b/cmd/crc/cmd/setup.go
> index e8cf8098..1b5322ad 100644
> --- a/cmd/crc/cmd/setup.go
> +++ b/cmd/crc/cmd/setup.go
> @@ -82,6 +82,9 @@ func (s *setupResult) prettyPrintTo(writer io.Writer) error {
>         if s.Error != nil {
>                 return s.Error
>         }
> +       if checksOnly {
> +               return nil
> +       }
>         _, err := fmt.Fprintf(writer, "Setup is complete, you can now run 'crc start%s' to start the OpenShift cluster\n", extraArguments())
>         return err
>  }
> ```

@praveenkumar, agree that the full message is a bit confusing. Maybe just change the message in checksOnly case? For example to "You can run 'crc start%s'..." (without the Setup is complete). The idea being that the message makes sense if all checks passed. WDYT?

2021-04-09 08:13 UTC, cfergeau commented
Maybe change the message to `Your system is correctly setup for using CodeReady Containers, you can now run 'crc start%s' to start the OpenShift cluster` which is correct in all cases (with and without `--check-only`)?

2021-04-09 08:49 UTC, jsliacan approved these changes
LGTM. Thanks!

2021-04-09 10:49 UTC, anjannath commented on cmd/crc/cmd/setup_test.go
> +	assert.Equal(t, "Your system is correctly setup for using CodeReady Containers, you can now run 'crc start -b $bundlename' to start the OpenShift cluster\n", out.String())
👍🏽

2021-04-09 10:50 UTC, anjannath approved these changes

2021-04-09 10:50 UTC, praveenkumar commented
/lgtm

2021-04-09 10:50 UTC, merged