Use enum for openshift operator statuses
code-ready/crc pull request #2330
Opened 2021-05-11 07:00 UTC by guillaumerose

2021-05-11 07:12 UTC, gbraad commented on pkg/crc/cluster/clusteroperator.go
> +			case openshiftapi.OperatorUpgradeable:
The correct spelling is `Upgradable`... Upgradeable is an accepted variant but looks bonkers.

2021-05-11 08:04 UTC, gbraad commented on pkg/crc/cluster/clusteroperator.go
> +			case openshiftapi.OperatorUpgradeable:
Ugh

2021-05-11 08:07 UTC, cfergeau commented on pkg/crc/cluster/clusteroperator.go
> +			case "Disabled": // non official status, used by insights and cluster baremetal operators
`OperatorDisabled` would be more consistent with the other constants.

2021-05-11 09:03 UTC, gbraad commented on pkg/crc/cluster/clusteroperator.go
> +			case "Disabled": // non official status, used by insights and cluster baremetal operators
We can define an internal state, like the noop case below in our own codebase.

2021-05-11 09:09 UTC, gbraad requested changes
Prevent string comparison; introduce a const that can easily be refactored/find references when needed.

2021-05-11 09:11 UTC, cfergeau commented
/lgtm

2021-05-12 04:48 UTC, anjannath approved these changes

2021-05-12 05:57 UTC, gbraad commented
it seems the majority does not care about maintainability; merging with a grudge

2021-05-12 05:58 UTC, gbraad commented
/retest

2021-05-12 05:58 UTC, merged