Check if running in WSL2 right after checking root
code-ready/crc pull request #2335
Opened 2021-05-11 12:48 UTC by guillaumerose

There is no point trying to install KVM, etc before checking for WSL2
installation.

Before:

$ crc setup
INFO Checking if running as non-root
INFO Checking if libvirt is installed
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if running inside WSL2
Your system is correctly setup for using CodeReady Containers

After:

$ crc setup
INFO Checking if running as non-root
INFO Checking if running inside WSL2
INFO Checking if libvirt is installed
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
Your system is correctly setup for using CodeReady Containers

2021-05-11 12:54 UTC, cfergeau approved these changes

2021-05-11 14:02 UTC, gbraad requested changes

2021-05-11 14:02 UTC, gbraad commented on pkg/crc/preflight/preflight_linux.go
> +	return getPreflightChecksForDistro(distro(), networkMode, usingSystemdResolved == nil)
Wouldn't the fix just be:
```golang
func getPreflightChecks(_ bool, _ bool, networkMode network.Mode) []Check {
	usingSystemdResolved := checkSystemdResolvedIsRunning()
	checks := wsl2PreflightChecks
	checks = append(checks, getPreflightChecksForDistro(distro(), networkMode, usingSystemdResolved == nil))
	return checks
}
```

2021-05-11 14:04 UTC, gbraad commented on pkg/crc/preflight/preflight_linux.go
> +	checks = append(checks, wsl2PreflightChecks)
This is confusing in my opinion... This is not a 'distro' check.
The naming of the preflights is very messy...

and this is not adjusted in the `GetAllPreflightChecks`?

2021-05-11 14:28 UTC, merged

2021-05-13 11:33 UTC, gbraad commented on pkg/crc/preflight/preflight_linux.go
> +	checks = append(checks, wsl2PreflightChecks)
I do appreciate the attempt there ;-)