Replace mirror link to developer.redhat.com
code-ready/crc pull request #2358
Opened 2021-05-19 12:52 UTC by praveenkumar

As of now developer.redhat.com link need to require cookie so
we create a cookieJar and pass it to the http.Client

2021-05-19 12:56 UTC, cfergeau commented
I'd hold this until we get confirmation we don't have a choice and cookies are required :)

2021-05-19 13:00 UTC, cfergeau approved these changes
Looks good to me

2021-05-19 13:00 UTC, cfergeau commented
/hold

2021-05-21 09:12 UTC, praveenkumar commented
/retest

2021-05-25 11:09 UTC, cfergeau requested changes
Cookies are no longer required to fetch from developers.redhat.com

2021-05-25 11:09 UTC, cfergeau commented
/unhold

2021-05-26 11:43 UTC, cfergeau commented on pkg/crc/version/version.go
> +	releaseInfoLink = "https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/1.26.0/release-info.json"
This has to be a `latest` link, not `1.26.0`, otherwise we won't be able to detect the newer version

2021-05-31 09:27 UTC, guillaumerose approved these changes

2021-06-01 06:21 UTC, merged