API: Add podman version to status result
code-ready/crc pull request #2892
Opened 2021-12-20 11:05 UTC by praveenkumar

This patch will add podman version to crc status result so that
during api status request it have version info.
```
$ curl -X GET --unix-socket ~/.crc/crc-http.sock http:/c/api/status  | jq .
{
  "CrcStatus": "Stopped",
  "OpenshiftStatus": "",
  "OpenshiftVersion": "",
  "PodmanVersion": "3.4.1",
  "DiskUse": 0,
  "DiskSize": 0,
  "Error": "",
  "Success": true
}
```

2021-12-20 11:10 UTC, gbraad commented
This is not acceptable.

Now I can't determine if this is Podman or OpenShift as the version inclusion is determining the used preset.

If you wanna go ahead with this, can we instead add an additional 'preset' ?

2021-12-20 11:11 UTC, gbraad commented on pkg/crc/api/handlers.go
> +		PodmanVersion:    res.PodmanVersion,
This adds too much information and makes it hard to determine the type:

![image](https://user-images.githubusercontent.com/1894/146758353-3d026829-cfba-40cb-a85f-8da2983b4e53.png)

can you either add `preset` or only add the necessary fields.

2021-12-20 11:11 UTC, gbraad requested changes
`preset` needed or only the known fields for the preset

2021-12-21 05:52 UTC, gbraad commented on pkg/crc/api/handlers.go
> +		PodmanVersion:    res.PodmanVersion,
Added in another PR

2021-12-21 05:52 UTC, gbraad commented
I prefer not to have unnecessary fields added to the result. But let's solve that in a later PR.

2021-12-21 05:54 UTC, gbraad approved these changes

2021-12-21 06:01 UTC, gbraad commented
Status command now shows:

```
PS> crc status
CRC VM:          Running
OpenShift:
Podman:          3.4.1
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     4.78GB
Cache Directory: C:\Users\gbraad\.crc\cache  
```

2021-12-21 06:03 UTC, gbraad commented
Also, the API returns:

```
CrcStatus: "Starting"
DiskSize: 0
DiskUse: 0
Error: ""
OpenshiftStatus: "Starting"
OpenshiftVersion: ""
PodmanVersion: ""
Preset: ""
Success: true
```

with an unknown preset. Is this rebased on the previous one?

2021-12-21 06:04 UTC, gbraad requested changes
~~.~~

2021-12-21 06:05 UTC, gbraad requested changes
Not working as expected.

Shows OpenShiftStatus and no preset

2021-12-21 06:11 UTC, gbraad commented
weird... now it shows.
Seems the startup of the daemon is unreliable?

2021-12-21 06:33 UTC, gbraad commented
> https://github.com/code-ready/crc/pull/2892#issuecomment-998498027

Let's create a new issue to resolve this forthe API and status command.

2021-12-21 09:14 UTC, praveenkumar commented
> > [#2892 (comment)](https://github.com/code-ready/crc/pull/2892#issuecomment-998498027)
> 
> Let's create a new issue to resolve this forthe API and status command.

https://github.com/code-ready/crc/issues/2898 

merging this one.

2021-12-21 09:14 UTC, merged