Vsock: Add ip to local port mapping
code-ready/crc pull request #2903
Opened 2021-12-24 07:15 UTC by praveenkumar

As of now, port expose happen on all the interface `:<port>`, with
this PR it happen only on the localhost/127.0.0.1 so other interface
are free to use for same port if required.

2021-12-24 13:41 UTC, praveenkumar commented
/retest

2021-12-30 14:35 UTC, gbraad commented
Will have to test this

2022-01-04 09:50 UTC, cfergeau reviewed
Not 100% sure what the usecase is for this/what concrete problems this will solve, could you detail a bit more in the commit log?
The daemon would bind only on 127.0.0.1:80, leaving 192.168.x.y:80 free for use by another webserver, but is this really something we want to encourage? Similarly, we could instruct users to configure sshd to listen on all IPs except localhost, and use 22 to access the VM instead of 2222, but I'm not sure it's going to be that convenient to configure over using 2222?

A side effect of this change is that https://github.com/code-ready/crc/issues/2667#issuecomment-915257243 would probably no longer work.

2022-01-04 09:50 UTC, cfergeau commented on pkg/crc/machine/vsock.go
> +	hostInterfaceIP  = "127.0.0.1"
I would drop the `Interface` from the name. Dunno if the right name is `host`, or just `localIP`, `loopbackIP`

2022-01-04 10:32 UTC, gbraad commented
> A side effect of this change is that #2667 (comment) would probably no longer work.

Can you confirm this?

2022-01-07 03:39 UTC, praveenkumar commented
/close

For cockpit following issues are created.
- https://github.com/code-ready/tray-electron/issues/30
- https://github.com/code-ready/crc/issues/2890

2022-01-07 08:19 UTC, praveenkumar commented
/open

2022-01-10 06:08 UTC, praveenkumar commented
> > A side effect of this change is that #2667 (comment) would probably no longer work.
> 
> Can you confirm this?

It will not work as it is but with documents, user can use something like following to make it work.

```
$ curl -X POST -d '{"local": "<external_ip>:6443", "remote": "192.168.127.2:6443"}'  --unix-socket ~/.crc/crc-http.sock http:/unix/network/services/forwarder/expose
```

2022-01-11 08:42 UTC, cfergeau commented
> It will not work as it is but with documents, user can use something like following to make it work.

But this is not going to be persistent, so will have to be redone after each VM reboot, or even more often than that when https://github.com/code-ready/crc/issues/2923 is solved.
The commit log does not reflect the most recent conversation we had about why it's desirable to make this change.

2022-01-11 10:17 UTC, cfergeau requested changes
https://github.com/code-ready/crc/pull/2903#issuecomment-1009717556

2022-01-17 08:16 UTC, praveenkumar commented
> > It will not work as it is but with documents, user can use something like following to make it work.
> 
> But this is not going to be persistent, so will have to be redone after each VM reboot, or even more often than that when #2923 is solved. 

Yes, that would be the limitation at the moment but it makes apiserver/cockpit more secure for unknown external access.

> The commit log does not reflect the most recent conversation we had about why it's desirable to make this change.

@cfergeau Updated the comment with recent discussion.

2022-01-17 15:56 UTC, praveenkumar commented
/retest

2022-01-18 08:34 UTC, cfergeau approved these changes

2022-01-18 08:56 UTC, merged

2022-01-18 16:56 UTC, cfergeau commented
Totally forgot a very important detail, on macOS, a regular user cannot bind on localhost-only, you need additional privileges for that. This broke `crc start` until I reverted this.